---
- name: Prepare
  hosts: all
  gather_facts: False
  become: true
  vars:
    ignore_assert_errors: true
  roles:
    - role: kubespray-defaults
    - role: bootstrap-os
    - { role: kubernetes/preinstall, tags: ["bootstrap-os"] }
